<?php
//
// File generated by ... on the 2014-07-21T21:27:53+0200
// Please do not edit manually
//

/**
 * Classes and menus for teemip-network-mgmt (version 2.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



class WANLink extends FunctionalCI
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,configmgmt',
			'key_type' => 'autoincrement',
			'name_attcode' => 'name',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id', 'organization_name'),
			'db_table' => 'wanlink',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'teemip-network-mgmt/images/wanlink.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("type", array("allowed_values"=>null, "sql"=>'type', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("status", array("allowed_values"=>new ValueSetEnum("stock,implementation,production,obsolete"), "display_style"=>'list', "sql"=>'status', "default_value"=>'production', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("location_id1", array("targetclass"=>'Location', "allowed_values"=>new ValueSetObjects("SELECT l FROM Organization AS child JOIN Organization AS root ON child.parent_id BELOW root.id JOIN Location AS l ON l.org_id=root.id WHERE child.id=:this->org_id"), "sql"=>'location_id1', "is_null_allowed"=>true, "on_target_delete"=>DEL_MANUAL, "depends_on"=>array('org_id'), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("location_name1", array("allowed_values"=>null, "extkey_attcode"=>'location_id1', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("location_id2", array("targetclass"=>'Location', "allowed_values"=>new ValueSetObjects("SELECT l FROM Organization AS child JOIN Organization AS root ON child.parent_id BELOW root.id JOIN Location AS l ON l.org_id=root.id WHERE child.id=:this->org_id"), "sql"=>'location_id2', "is_null_allowed"=>true, "on_target_delete"=>DEL_MANUAL, "depends_on"=>array('org_id'), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("location_name2", array("allowed_values"=>null, "extkey_attcode"=>'location_id2', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("carrier", array("allowed_values"=>null, "sql"=>'carrier', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("carrier_reference", array("allowed_values"=>null, "sql"=>'carrier_ref', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("networkinterface_id1", array("targetclass"=>'NetworkInterface', "allowed_values"=>null, "sql"=>'networkinterface_id1', "is_null_allowed"=>true, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("networkinterface_name1", array("allowed_values"=>null, "extkey_attcode"=>'networkinterface_id1', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("networkinterface_id2", array("targetclass"=>'NetworkInterface', "allowed_values"=>null, "sql"=>'networkinterface_id2', "is_null_allowed"=>true, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("networkinterface_name2", array("allowed_values"=>null, "extkey_attcode"=>'networkinterface_id2', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("purchase_date", array("allowed_values"=>null, "sql"=>'purchase_date', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("renewal_date", array("allowed_values"=>null, "sql"=>'renewal_date', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));


		MetaModel::Init_SetZListItems('details', array (
  'col:col1' => 
  array (
    'fieldset:Class:WANLink:baseinfo' => 
    array (
      0 => 'name',
      1 => 'org_id',
      2 => 'description',
      3 => 'status',
      4 => 'location_id1',
      5 => 'location_id2',
      6 => 'networkinterface_id1',
      7 => 'networkinterface_id2',
    ),
    0 => 'contacts_list',
    1 => 'documents_list',
    2 => 'tickets_list',
    3 => 'providercontracts_list',
  ),
  'col:col2' => 
  array (
    'fieldset:Class:WANLink:carrierinfo' => 
    array (
      0 => 'carrier',
      1 => 'carrier_reference',
      2 => 'move2production',
      3 => 'purchase_date',
      4 => 'renewal_date',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'org_id',
  2 => 'status',
  3 => 'carrier',
  4 => 'carrier_reference',
  5 => 'move2production',
  6 => 'purchase_date',
  7 => 'renewal_date',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'status',
  1 => 'type',
  2 => 'location_id1',
  3 => 'location_id2',
  4 => 'carrier',
  5 => 'carrier_reference',
  6 => 'networkinterface_id1',
  7 => 'networkinterface_id2',
  8 => 'org_id',
));

	}


}


class ASNumber extends FunctionalCI
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,configmgmt',
			'key_type' => 'autoincrement',
			'name_attcode' => 'name',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id', 'organization_name'),
			'db_table' => 'asnumber',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'teemip-network-mgmt/images/asnumber.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeDecimal("number", array("allowed_values"=>null, "sql"=>'number', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "digits"=>10, "decimals"=>0, "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("registrar", array("allowed_values"=>null, "sql"=>'registrar', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeURL("whois", array("target"=>'', "allowed_values"=>null, "sql"=>'whois', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("validity_end", array("allowed_values"=>null, "sql"=>'validity_end', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("renewal_date", array("allowed_values"=>null, "sql"=>'renewal_date', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));


		MetaModel::Init_SetZListItems('details', array (
  'col:col1' => 
  array (
    'fieldset:Class:ASNumber:baseinfo' => 
    array (
      0 => 'name',
      1 => 'number',
      2 => 'org_id',
      3 => 'description',
    ),
  ),
  'col:col2' => 
  array (
    'fieldset:Class:ASNumber:admininfo' => 
    array (
      0 => 'registrar',
      1 => 'whois',
      2 => 'move2production',
      3 => 'validity_end',
      4 => 'renewal_date',
    ),
  ),
  0 => 'contacts_list',
  1 => 'documents_list',
  2 => 'providercontracts_list',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'number',
  2 => 'org_id',
  3 => 'registrar',
  4 => 'move2production',
  5 => 'validity_end',
  6 => 'renewal_date',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'number',
  1 => 'registrar',
  2 => 'validity_end',
  3 => 'org_id',
));

	}


}


abstract class DNSObject extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,ipmgmt,dnsmgmt',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id', 'org_name'),
			'db_table' => 'dnsobject',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("org_id", array("targetclass"=>'Organization', "allowed_values"=>null, "sql"=>'org_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_MANUAL, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("org_name", array("allowed_values"=>null, "extkey_attcode"=>'org_id', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDomainName("name", array("allowed_values"=>null, "sql"=>'name', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("comment", array("allowed_values"=>null, "sql"=>'comment', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



	}


}



require_once('_domain.class.inc.php'); // Implementation of the class _Domain
class Domain extends _Domain
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,dnsmgmt',
			'key_type' => 'autoincrement',
			'name_attcode' => 'name',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id', 'org_name'),
			'db_table' => 'domain',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'teemip-network-mgmt/images/domain.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeHierarchicalKey("parent_id", array("allowed_values"=>new ValueSetObjects("SELECT Domain AS d WHERE d.org_id = :this->org_id"), "sql"=>'parent_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_MOVEUP, "depends_on"=>array('org_id'), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("parent_name", array("allowed_values"=>null, "extkey_attcode"=>'parent_id', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("requestor_id", array("targetclass"=>'Person', "allowed_values"=>new ValueSetObjects("SELECT Person AS p WHERE p.org_id = :this->org_id"), "sql"=>'requestor_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_MANUAL, "depends_on"=>array('org_id'), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("requestor_name", array("allowed_values"=>null, "extkey_attcode"=>'requestor_id', "target_attcode"=>'name', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("release_date", array("allowed_values"=>null, "sql"=>'release_date', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("registrar", array("allowed_values"=>null, "sql"=>'registrar', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("validity_start", array("allowed_values"=>null, "sql"=>'validity_start', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("validity_end", array("allowed_values"=>null, "sql"=>'validity_end', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("renewal", array("allowed_values"=>new ValueSetEnum("na,manual,automatic"), "display_style"=>'list', "sql"=>'renewal', "default_value"=>'na', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));


		MetaModel::Init_SetZListItems('details', array (
  'col:col1' => 
  array (
    'fieldset:Class:Domain:baseinfo' => 
    array (
      0 => 'org_id',
      1 => 'parent_id',
      2 => 'name',
      3 => 'comment',
      4 => 'requestor_id',
      5 => 'release_date',
    ),
  ),
  'col:col2' => 
  array (
    'fieldset:Class:Domain:admininfo' => 
    array (
      0 => 'registrar',
      1 => 'validity_start',
      2 => 'validity_end',
      3 => 'renewal',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'parent_id',
  2 => 'registrar',
  3 => 'validity_end',
  4 => 'renewal',
  5 => 'org_id',
  6 => 'requestor_id',
  7 => 'release_date',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'parent_id',
  1 => 'comment',
  2 => 'registrar',
  3 => 'org_id',
));

	}


}